name: "Override Pull-request attestation"
description: "Override a Pull-request attestation"
inputs:
  kosli_api_token:
    description: "The Kosli API token for authorization"
    required: true
  kosli_org:
    description: "The Kosli organization"
    required: true
  kosli_flow_name:
    description: "The Kosli flow for the pull-request override"
    required: true
  kosli_trail_name:
    description: "The Kosli trail for the pull-request override"
    required: true
  attestation_name:
    description: "The name of the pull_request attestation we want to override"
    required: true
  override_reason:
    description: "The reason for the override"
    required: true
  override_compliance:
    description: "Compliance value for override"
    type: boolean
    required: true
  kosli_host_name:
    description: "The Kosli host name"
    required: false
    default: "https://app.kosli.com"

runs:
  using: "composite"
  steps:
    - name: Override
      shell: bash
      run: | 
        OUTPUT_FILE=$(mktemp)
        JSON_PAYLOAD='{"attestation_name": "${{ inputs.attestation_name }}", "original_attestation_type": "pull_request", "reason": "${{ inputs.override_reason }}", "new_compliance_status": ${{ inputs.override_compliance }}, "annotations": { "Reason": "${{ inputs.override_reason }}" } }'
        set +e
        HTTP_CODE=$(curl -X 'POST' \
          "${{ inputs.kosli_host_name }}/api/fastapi/attestations/${{ inputs.kosli_org }}/${{ inputs.kosli_flow_name }}/trail/${{ inputs.kosli_trail_name }}/override" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ inputs.kosli_api_token }}" \
          --output "${OUTPUT_FILE}" \
          --data "${JSON_PAYLOAD}" \
          --write-out "%{http_code}" \
          --silent)
        set -e
        echo -n .
        if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
            >&2 cat "${OUTPUT_FILE}"
            rm "${OUTPUT_FILE}"
            exit 22
        fi
