name: Run Tests

on:
  push:
    paths:
      - 'code-review/**'
  pull_request:
    paths:
      - 'code-review/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Run tests
      run: |
        cd code-review
        make test